<?php
require_once __DIR__ . '/../../src/config/database.php';
require_once __DIR__ . '/../../src/config/Database.php';
require_once __DIR__ . '/../../src/middleware/Auth.php';
require_once __DIR__ . '/../../src/models/Admin.php';
Auth::requireRole('admin', '/auth/login.php');
if (!PORTAL_EXTENSIONS_ENABLED) { http_response_code(503); exit('Admin tools are disabled.'); }
Admin::ensureAuditTable();
$user = Auth::user();
$stats = Admin::stats();
$pendingLecturers = PORTAL_EXTENSIONS_ENABLED ? Admin::pendingLecturers() : [];
$search = trim($_GET['q'] ?? '');
$role = $_GET['role'] ?? '';
$page = max(1, (int)($_GET['page'] ?? 1));
$userPage = Admin::users($search, $role, $page);
$payments = PORTAL_EXTENSIONS_ENABLED ? Admin::payments(['status' => $_GET['payment_status'] ?? '', 'course_id' => $_GET['course_id'] ?? '', 'student_id' => $_GET['student_id'] ?? '', 'date_from' => $_GET['date_from'] ?? '', 'date_to' => $_GET['date_to'] ?? '']) : [];
$courseOptions = Database::query('SELECT id, code, title FROM courses ORDER BY title')->fetchAll();
$educationCounts = EDUCATION_COURSE_TARGETING_ENABLED
	? Database::query("SELECT COALESCE(education_level, 'unknown') AS education_level, COUNT(*) AS total FROM users WHERE role = 'student' GROUP BY education_level")->fetchAll()
	: [];
$security = PORTAL_EXTENSIONS_ENABLED ? Admin::securitySummary() : ['pending_payments'=>0,'failed_callbacks'=>0,'suspended_users'=>0,'audit_events_24h'=>0,'unmatched_paid_enrollments'=>0];
$health = Admin::health();
$audit = PORTAL_EXTENSIONS_ENABLED ? Admin::recentAudit(50) : [];
$metrics = Admin::systemMetrics();
$siteSettings = [];
if (PORTAL_EXTENSIONS_ENABLED) {
	foreach (['maintenance_mode','new_registrations_enabled','student_course_applications_enabled','payments_enabled'] as $settingKey) {
		$siteSettings[$settingKey] = Admin::setting($settingKey, $settingKey === 'payments_enabled' ? '0' : '1');
	}
}
$courses = PORTAL_EXTENSIONS_ENABLED
 ? Database::query('SELECT c.id, c.code, c.title, c.status, c.price, u.name AS lecturer_name, (SELECT COUNT(*) FROM enrollments e WHERE e.course_id = c.id) AS enrollments, (SELECT COALESCE(SUM(p.amount_paid),0) FROM payments p WHERE p.course_id = c.id AND p.payment_status = \'success\') AS revenue FROM courses c JOIN users u ON u.id = c.lecturer_id ORDER BY c.created_at DESC LIMIT 200')->fetchAll()
 : Database::query('SELECT c.id, c.code, c.title, \'published\' AS status, NULL AS price, u.name AS lecturer_name, (SELECT COUNT(*) FROM enrollments e WHERE e.course_id = c.id) AS enrollments, 0 AS revenue FROM courses c JOIN users u ON u.id = c.lecturer_id ORDER BY c.created_at DESC LIMIT 200')->fetchAll();
$flash = $_SESSION['flash'] ?? null; unset($_SESSION['flash']);
$pageTitle = 'Admin Dashboard';
?>
<?php include __DIR__ . '/../../views/shared/header.php'; ?>
<div class="page-header"><div><h1 class="page-title">Admin Dashboard</h1><p class="page-subtitle">Administrative actions are recorded in the audit log.</p></div></div>
<div class="stats-grid"><div class="stat-card"><div class="stat-number"><?= $stats['users'] ?></div><div class="stat-label">Users</div></div><div class="stat-card"><div class="stat-number"><?= $stats['courses'] ?></div><div class="stat-label">Published courses</div></div><div class="stat-card"><div class="stat-number"><?= $stats['pending'] ?></div><div class="stat-label">Pending lecturer approvals</div></div><div class="stat-card"><div class="stat-number">KES <?= number_format($stats['revenue'],2) ?></div><div class="stat-label">Confirmed revenue</div></div></div>
<div class="card"><div class="card-header"><h2 class="card-title">System activity metrics</h2></div><div class="stats-grid"><div class="stat-card"><div class="stat-number"><?= $metrics['students'] ?></div><div class="stat-label">Students</div></div><div class="stat-card"><div class="stat-number"><?= $metrics['lecturers'] ?></div><div class="stat-label">Lecturers</div></div><div class="stat-card"><div class="stat-number"><?= $metrics['tutors'] ?></div><div class="stat-label">Tutors</div></div><div class="stat-card"><div class="stat-number"><?= $metrics['active_enrollments'] ?></div><div class="stat-label">Approved enrollments</div></div><div class="stat-card"><div class="stat-number"><?= $metrics['submissions'] ?></div><div class="stat-label">Submissions</div></div><div class="stat-card"><div class="stat-number"><?= $metrics['graded'] ?></div><div class="stat-label">Graded submissions</div></div><div class="stat-card"><div class="stat-number"><?= $metrics['active_sessions'] ?></div><div class="stat-label">Upcoming sessions</div></div></div></div>
<div class="card"><div class="card-header"><h2 class="card-title">Student education levels</h2></div><div class="d-flex gap-2"><?php foreach ($educationCounts as $educationCount): ?><span class="badge badge-info"><?= htmlspecialchars(ucwords(str_replace('_', ' ', $educationCount['education_level']))) ?>: <?= (int)$educationCount['total'] ?></span><?php endforeach; ?></div></div>
<div class="stats-grid"><div class="stat-card"><div class="stat-number"><?= $security['pending_payments'] ?></div><div class="stat-label">Pending M-Pesa</div></div><div class="stat-card"><div class="stat-number"><?= $security['failed_callbacks'] ?></div><div class="stat-label">Callbacks needing retry</div></div><div class="stat-card"><div class="stat-number"><?= $security['suspended_users'] ?></div><div class="stat-label">Suspended accounts</div></div><div class="stat-card"><div class="stat-number"><?= $security['audit_events_24h'] ?></div><div class="stat-label">Audit events (24h)</div></div><div class="stat-card"><div class="stat-number"><?= $security['unmatched_paid_enrollments'] ?></div><div class="stat-label">Approved but unpaid applications</div></div></div>
<div class="card"><div class="card-header"><h2 class="card-title">Site health &amp; configuration checks</h2></div><ul><?php foreach ($health as $check => $ok): ?><li><span class="badge badge-<?= $ok ? 'success' : 'warning' ?>"><?= $ok ? 'OK' : 'CHECK' ?></span> <?= htmlspecialchars(ucwords(str_replace('_', ' ', $check))) ?></li><?php endforeach; ?></ul><p class="form-hint">Health checks report configuration presence only; secrets are never shown.</p></div>
<?php if (PORTAL_EXTENSIONS_ENABLED): ?><div class="card" id="site-controls"><div class="card-header"><h2 class="card-title">Site feature controls</h2></div><?php foreach ($siteSettings as $settingKey => $settingValue): ?><form method="POST" action="/admin/action.php" class="d-flex gap-1" style="padding:.5rem 0"><input type="hidden" name="csrf_token" value="<?= Auth::csrfToken() ?>"><input type="hidden" name="setting_key" value="<?= htmlspecialchars($settingKey) ?>"><strong style="min-width:18rem"><?= htmlspecialchars(ucwords(str_replace('_',' ',$settingKey))) ?></strong><select name="setting_value"><option value="1" <?= $settingValue==='1'?'selected':'' ?>>Enabled</option><option value="0" <?= $settingValue==='0'?'selected':'' ?>>Disabled</option></select><button class="btn btn-secondary btn-sm" name="action" value="update_setting">Save</button></form><?php endforeach; ?><p class="form-hint">Payments also require MPESA_ENABLED=true and valid Daraja configuration. Feature settings are audited.</p></div><?php endif; ?>
	<div class="card" id="lecturer-approvals"><div class="card-header"><h2 class="card-title">Lecturer approvals</h2></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Applied</th><th>Action</th></tr></thead><tbody><?php foreach ($pendingLecturers as $lecturer): ?><tr><td><?= htmlspecialchars($lecturer['name']) ?></td><td><?= htmlspecialchars($lecturer['email']) ?></td><td><?= htmlspecialchars($lecturer['created_at']) ?></td><td><form method="POST" action="/admin/action.php" style="display:flex;gap:.5rem"><input type="hidden" name="csrf_token" value="<?= Auth::csrfToken() ?>"><input type="hidden" name="lecturer_id" value="<?= (int)$lecturer['id'] ?>"><input name="note" maxlength="500" placeholder="Note (optional)"><button class="btn btn-success btn-sm" name="action" value="approve">Approve</button><button class="btn btn-danger btn-sm" name="action" value="reject">Reject</button></form></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="card" id="users"><div class="card-header"><h2 class="card-title">Users</h2></div><form method="GET" class="d-flex gap-1"><input name="q" value="<?= htmlspecialchars($search) ?>" placeholder="Search name or email"><select name="role"><option value="">All roles</option><?php foreach (['student','lecturer','tutor','admin'] as $r): ?><option <?= $role === $r ? 'selected' : '' ?>><?= $r ?></option><?php endforeach; ?></select><button class="btn btn-secondary">Search</button></form><div class="table-wrap"><table><thead><tr><th>User</th><th>Role</th><?php if(PORTAL_EXTENSIONS_ENABLED): ?><th>Account</th><th>Lecturer approval</th><?php endif; ?><th>Actions</th></tr></thead><tbody><?php foreach ($userPage['rows'] as $row): ?><tr><td><?= htmlspecialchars($row['name']) ?><br><small><?= htmlspecialchars($row['email']) ?></small></td><td><?= htmlspecialchars($row['role']) ?></td><?php if(PORTAL_EXTENSIONS_ENABLED): ?><td><?= htmlspecialchars($row['account_status']) ?></td><td><?= htmlspecialchars($row['lecturer_approval_status'] ?? '—') ?></td><?php endif; ?><td><?php if(PORTAL_EXTENSIONS_ENABLED): ?><form method="POST" action="/admin/action.php" class="d-flex gap-1"><input type="hidden" name="csrf_token" value="<?= Auth::csrfToken() ?>"><input type="hidden" name="user_id" value="<?= (int)$row['id'] ?>"><select name="role"><?php foreach (['student','lecturer','tutor','admin'] as $r): ?><option value="<?= $r ?>" <?= $row['role'] === $r ? 'selected' : '' ?>><?= $r ?></option><?php endforeach; ?></select><select name="account_status"><option value="active" <?= $row['account_status'] === 'active' ? 'selected' : '' ?>>active</option><option value="suspended" <?= $row['account_status'] === 'suspended' ? 'selected' : '' ?>>suspended</option></select><button class="btn btn-secondary btn-sm" name="action" value="update_user">Save</button></form><form method="POST" action="/admin/action.php" onsubmit="return confirm('Delete this account only if it has no retained enrolment, submission, or payment history?')" style="margin-top:.4rem"><input type="hidden" name="csrf_token" value="<?= Auth::csrfToken() ?>"><input type="hidden" name="user_id" value="<?= (int)$row['id'] ?>"><button class="btn btn-danger btn-sm" name="action" value="delete_user">Delete (no history only)</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><p class="form-hint">Page <?= $page ?> of <?= max(1,$userPage['pages']) ?> · <?= $userPage['total'] ?> users</p></div>
<div class="card" id="courses"><div class="card-header"><h2 class="card-title">Courses</h2></div><div class="table-wrap"><table><thead><tr><th>Course</th><th>Lecturer</th><th>Status</th><th>Enrollments</th><th>Revenue</th><th>Fee (KES)</th><th>Actions</th></tr></thead><tbody><?php foreach ($courses as $course): ?><tr><td><?= htmlspecialchars($course['code'].' — '.$course['title']) ?></td><td><?= htmlspecialchars($course['lecturer_name']) ?></td><td><?= htmlspecialchars($course['status']) ?></td><td><?= (int)$course['enrollments'] ?></td><td>KES <?= number_format((float)$course['revenue'],2) ?></td><td><?php if (PORTAL_EXTENSIONS_ENABLED): ?><form method="POST" action="/admin/action.php" class="d-flex gap-1"><input type="hidden" name="csrf_token" value="<?= Auth::csrfToken() ?>"><input type="hidden" name="course_id" value="<?= (int)$course['id'] ?>"><input name="price" type="number" min="0" max="1000000" step="1" value="<?= htmlspecialchars((string)($course['price'] ?? '')) ?>" placeholder="Free"><button class="btn btn-secondary btn-sm" name="action" value="update_course_fee">Save</button></form><?php else: ?>—<?php endif; ?></td><td><form method="POST" action="/admin/action.php"><input type="hidden" name="csrf_token" value="<?= Auth::csrfToken() ?>"><input type="hidden" name="course_id" value="<?= (int)$course['id'] ?>"><?php if ($course['status'] === 'suspended'): ?><button class="btn btn-success btn-sm" name="action" value="restore_course">Restore</button><?php else: ?><button class="btn btn-danger btn-sm" name="action" value="suspend_course">Suspend</button><?php endif; ?></form></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="card" id="payments"><div class="card-header"><h2 class="card-title">Payments</h2></div><form method="GET"><select name="payment_status"><option value="">All statuses</option><?php foreach (['pending','success','failed'] as $status): ?><option value="<?= $status ?>" <?= ($_GET['payment_status'] ?? '') === $status ? 'selected' : '' ?>><?= $status ?></option><?php endforeach; ?></select><select name="course_id"><option value="">All courses</option><?php foreach ($courseOptions as $courseOption): ?><option value="<?= (int)$courseOption['id'] ?>" <?= (int)($_GET['course_id'] ?? 0)===(int)$courseOption['id']?'selected':'' ?>><?= htmlspecialchars($courseOption['code'].' — '.$courseOption['title']) ?></option><?php endforeach; ?></select><input name="student_id" type="number" min="1" placeholder="Student ID" value="<?= htmlspecialchars($_GET['student_id'] ?? '') ?>"><label>From <input name="date_from" type="date" value="<?= htmlspecialchars($_GET['date_from'] ?? '') ?>"></label><label>To <input name="date_to" type="date" value="<?= htmlspecialchars($_GET['date_to'] ?? '') ?>"></label><button class="btn btn-secondary btn-sm">Filter</button></form><div class="table-wrap"><table><thead><tr><th>Student</th><th>Course</th><th>Amount</th><th>Status</th><th>Receipt</th><th>Date</th></tr></thead><tbody><?php foreach ($payments as $payment): ?><tr><td><?= htmlspecialchars($payment['student_name']) ?></td><td><?= htmlspecialchars($payment['course_title']) ?></td><td>KES <?= number_format((float)$payment['amount_paid'],2) ?></td><td><?= htmlspecialchars($payment['payment_status']) ?></td><td><?= htmlspecialchars($payment['mpesa_receipt'] ?? '—') ?></td><td><?= htmlspecialchars($payment['created_at']) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="card" id="audit-log"><div class="card-header"><h2 class="card-title">Recent security/admin audit events</h2></div><div class="table-wrap"><table><thead><tr><th>Time</th><th>Administrator</th><th>Action</th><th>Target</th></tr></thead><tbody><?php foreach ($audit as $event): ?><tr><td><?= htmlspecialchars($event['created_at']) ?></td><td><?= htmlspecialchars($event['admin_name'] ?? 'System') ?></td><td><?= htmlspecialchars($event['action']) ?></td><td><?= htmlspecialchars($event['target_type'] . ' ' . ($event['target_id'] ?? '')) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php include __DIR__ . '/../../views/shared/footer.php'; ?>
