<?php
require_once __DIR__ . '/../../src/config/database.php';
require_once __DIR__ . '/../../src/config/Database.php';
require_once __DIR__ . '/../../src/middleware/Auth.php';
require_once __DIR__ . '/../../src/models/Admin.php';
require_once __DIR__ . '/../../src/models/RevisionPaper.php';
require_once __DIR__ . '/../../src/models/PageView.php';
Auth::requireRole('admin', '/auth/login.php');
Admin::ensureAuditTable();
$user = Auth::user();
$stats = Admin::stats();
$pendingLecturers = PORTAL_EXTENSIONS_ENABLED ? Admin::pendingLecturers() : [];
$search = trim($_GET['q'] ?? '');
$role = $_GET['role'] ?? '';
$page = max(1, (int)($_GET['page'] ?? 1));
$userPage = Admin::users($search, $role, $page);
$payments = PORTAL_EXTENSIONS_ENABLED ? Admin::payments(['status' => $_GET['payment_status'] ?? '', 'course_id' => $_GET['course_id'] ?? '', 'student_id' => $_GET['student_id'] ?? '', 'date_from' => $_GET['date_from'] ?? '', 'date_to' => $_GET['date_to'] ?? '']) : [];
$courseOptions = Database::query('SELECT id, code, title FROM courses ORDER BY title')->fetchAll();
$educationCounts = EDUCATION_COURSE_TARGETING_ENABLED
	? Database::query("SELECT COALESCE(education_level, 'unknown') AS education_level, COUNT(*) AS total FROM users WHERE role = 'student' GROUP BY education_level")->fetchAll()
	: [];
$security = PORTAL_EXTENSIONS_ENABLED ? Admin::securitySummary() : ['pending_payments'=>0,'failed_callbacks'=>0,'suspended_users'=>0,'audit_events_24h'=>0,'unmatched_paid_enrollments'=>0];
$health = Admin::health();
$paymentReadiness = Admin::paymentReadiness();
$audit = PORTAL_EXTENSIONS_ENABLED ? Admin::recentAudit(50) : [];
$metrics = Admin::systemMetrics();
$revisionSummary = RevisionPaper::adminSummary();
$pageViews = PORTAL_EXTENSIONS_ENABLED ? PageView::adminSummary() : ['today' => 0, 'last7' => 0, 'last30' => 0, 'by_role' => [], 'top_routes' => [], 'daily' => []];
$maxDailyPageViews = 1;
foreach ($pageViews['daily'] as $dailyView) {
	$maxDailyPageViews = max($maxDailyPageViews, (int)$dailyView['views']);
}
$siteSettings = [];
if (PORTAL_EXTENSIONS_ENABLED) {
	foreach (['maintenance_mode','new_registrations_enabled','student_course_applications_enabled','payments_enabled'] as $settingKey) {
		$siteSettings[$settingKey] = Admin::setting($settingKey, $settingKey === 'payments_enabled' ? '0' : '1');
	}
}
$courses = PORTAL_EXTENSIONS_ENABLED
 ? Database::query('SELECT c.id, c.code, c.title, c.status, c.price, u.name AS lecturer_name, (SELECT COUNT(*) FROM enrollments e WHERE e.course_id = c.id) AS enrollments, (SELECT COALESCE(SUM(p.amount_paid),0) FROM payments p WHERE p.course_id = c.id AND p.payment_status = \'success\') AS revenue FROM courses c JOIN users u ON u.id = c.lecturer_id ORDER BY c.created_at DESC LIMIT 200')->fetchAll()
 : Database::query('SELECT c.id, c.code, c.title, \'published\' AS status, NULL AS price, u.name AS lecturer_name, (SELECT COUNT(*) FROM enrollments e WHERE e.course_id = c.id) AS enrollments, 0 AS revenue FROM courses c JOIN users u ON u.id = c.lecturer_id ORDER BY c.created_at DESC LIMIT 200')->fetchAll();
$flash = $_SESSION['flash'] ?? null; unset($_SESSION['flash']);
$pageTitle = 'Admin Dashboard';
?>
<?php include __DIR__ . '/../../views/shared/header.php'; ?>
<div class="page-header"><div><h1 class="page-title">Admin Dashboard</h1><p class="page-subtitle">Administrative actions are recorded in the audit log.</p></div></div>
<?php if (!PORTAL_EXTENSIONS_ENABLED): ?><div class="alert alert-warning"><i class="fa fa-triangle-exclamation"></i><div><strong>Extended admin and lecturer features are switched off in this web process.</strong><p>Database migrations may already be applied; this message is controlled by the Render environment variable, not by your database login. In Render → this web service → Environment, set <strong>PORTAL_EXTENSIONS_ENABLED</strong> to <strong>true</strong>, save, then redeploy/restart the service. Keep payments disabled until M-Pesa setup is complete.</p></div></div><?php endif; ?>
<div class="card admin-quick-actions"><div class="card-header"><div><h2 class="card-title">Admin workspace</h2><p class="form-hint">Jump to reviews, platform controls, or learning content.</p></div></div><div class="admin-action-grid"><a class="admin-action-tile" href="#lecturer-approvals"><i class="fa fa-user-check"></i><span><strong>Review lecturers</strong><small><?= (int)$metrics['pending_lecturer_approvals'] ?> awaiting approval</small></span></a><a class="admin-action-tile" href="#users"><i class="fa fa-users"></i><span><strong>Manage accounts</strong><small>Search roles and account status</small></span></a><a class="admin-action-tile" href="#courses"><i class="fa fa-book-open"></i><span><strong>Manage courses</strong><small><?= (int)$metrics['draft_courses'] ?> drafts · set course fees</small></span></a><a class="admin-action-tile" href="#revision-papers"><i class="fa fa-file-circle-check"></i><span><strong>Revision library</strong><small><?= (int)$revisionSummary['published'] ?> published papers</small></span></a><a class="admin-action-tile" href="#site-controls"><i class="fa fa-sliders"></i><span><strong>Site controls</strong><small><?= (int)$metrics['pending_applications'] ?> pending course applications</small></span></a><a class="admin-action-tile" href="#audit-log"><i class="fa fa-shield-halved"></i><span><strong>Security activity</strong><small><?= (int)$security['audit_events_24h'] ?> audit events in 24 hours</small></span></a></div></div>
<div class="stats-grid page-view-stat-grid"><div class="stat-card"><div class="stat-number"><?= number_format($pageViews['today']) ?></div><div class="stat-label">Page views today</div><i class="fa fa-eye stat-icon"></i></div><div class="stat-card"><div class="stat-number text-blue"><?= number_format($pageViews['last7']) ?></div><div class="stat-label">Page views · 7 days</div><i class="fa fa-chart-line stat-icon"></i></div><div class="stat-card"><div class="stat-number text-green"><?= number_format($pageViews['last30']) ?></div><div class="stat-label">Page views · 30 days</div><i class="fa fa-chart-column stat-icon"></i></div></div>
<div class="card" id="page-analytics"><div class="card-header"><div><h2 class="card-title"><i class="fa fa-chart-line text-accent"></i> Page analytics</h2><p class="form-hint">Counts successful page requests, not unique people; reloads and bots may count. No IP addresses, user IDs, session IDs, or query strings are stored. Data is retained for up to 90 days.</p></div></div><?php if ($pageViews['daily']): ?><section class="page-views-trend"><h3 class="analytics-subtitle">Daily page requests · last 14 days</h3><div class="page-views-bars" role="img" aria-label="Daily page request counts over the last 14 days"><?php foreach ($pageViews['daily'] as $day): $height = max(5, (int)round(100 * (int)$day['views'] / $maxDailyPageViews)); ?><div class="page-views-day" title="<?= htmlspecialchars($day['day']) ?>: <?= (int)$day['views'] ?> requests"><span class="page-views-day-count"><?= (int)$day['views'] ?></span><span class="page-views-bar" style="height:<?= $height ?>%"></span><span class="page-views-day-label"><?= htmlspecialchars(date('M j', strtotime($day['day']))) ?></span></div><?php endforeach; ?></div></section><?php endif; ?><div class="admin-analytics-grid"><section><h3 class="analytics-subtitle">Most viewed pages · 30 days</h3><?php if ($pageViews['top_routes']): ?><div class="table-wrap"><table><thead><tr><th>Page</th><th>Views</th></tr></thead><tbody><?php foreach ($pageViews['top_routes'] as $route): ?><tr><td><code><?= htmlspecialchars($route['route']) ?></code></td><td class="fw-700"><?= number_format((int)$route['views']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><p class="text-muted">No page-view data yet. It starts accumulating after deployment.</p><?php endif; ?></section><section><h3 class="analytics-subtitle">Views by account role · 30 days</h3><?php if ($pageViews['by_role']): ?><div class="analytics-role-list"><?php foreach ($pageViews['by_role'] as $roleViews): ?><div><span class="badge badge-<?= in_array($roleViews['viewer_role'], ['student','lecturer','admin'], true) ? $roleViews['viewer_role'] : 'info' ?>"><?= htmlspecialchars(ucfirst($roleViews['viewer_role'])) ?></span><strong><?= number_format((int)$roleViews['views']) ?></strong></div><?php endforeach; ?></div><?php else: ?><p class="text-muted">Role breakdown will appear as pages are visited.</p><?php endif; ?></section></div></div>
<div class="stats-grid"><div class="stat-card"><div class="stat-number"><?= $stats['users'] ?></div><div class="stat-label">Users</div></div><div class="stat-card"><div class="stat-number"><?= $stats['courses'] ?></div><div class="stat-label">Published courses</div></div><div class="stat-card"><div class="stat-number"><?= $stats['pending'] ?></div><div class="stat-label">Pending lecturer approvals</div></div><div class="stat-card"><div class="stat-number">KES <?= number_format($stats['revenue'],2) ?></div><div class="stat-label">Confirmed revenue</div></div></div>
<div class="card"><div class="card-header"><h2 class="card-title">System activity metrics</h2></div><div class="stats-grid"><div class="stat-card"><div class="stat-number"><?= $metrics['students'] ?></div><div class="stat-label">Students</div></div><div class="stat-card"><div class="stat-number"><?= $metrics['lecturers'] ?></div><div class="stat-label">Lecturers</div></div><div class="stat-card"><div class="stat-number"><?= $metrics['tutors'] ?></div><div class="stat-label">Tutors</div></div><div class="stat-card"><div class="stat-number"><?= $metrics['active_enrollments'] ?></div><div class="stat-label">Approved enrollments</div></div><div class="stat-card"><div class="stat-number"><?= $metrics['submissions'] ?></div><div class="stat-label">Submissions</div></div><div class="stat-card"><div class="stat-number"><?= $metrics['graded'] ?></div><div class="stat-label">Graded submissions</div></div><div class="stat-card"><div class="stat-number"><?= $metrics['active_sessions'] ?></div><div class="stat-label">Upcoming sessions</div></div></div></div>
<div class="card"><div class="card-header"><h2 class="card-title">Student education levels</h2></div><div class="d-flex gap-2"><?php foreach ($educationCounts as $educationCount): ?><span class="badge badge-info"><?= htmlspecialchars(ucwords(str_replace('_', ' ', $educationCount['education_level']))) ?>: <?= (int)$educationCount['total'] ?></span><?php endforeach; ?></div></div>
<div class="stats-grid"><div class="stat-card"><div class="stat-number"><?= $security['pending_payments'] ?></div><div class="stat-label">Pending M-Pesa</div></div><div class="stat-card"><div class="stat-number"><?= $security['failed_callbacks'] ?></div><div class="stat-label">Callbacks needing retry</div></div><div class="stat-card"><div class="stat-number"><?= $security['suspended_users'] ?></div><div class="stat-label">Suspended accounts</div></div><div class="stat-card"><div class="stat-number"><?= $security['audit_events_24h'] ?></div><div class="stat-label">Audit events (24h)</div></div><div class="stat-card"><div class="stat-number"><?= $security['unmatched_paid_enrollments'] ?></div><div class="stat-label">Approved but unpaid applications</div></div></div>
<section class="card admin-revision-overview" id="revision-papers"><div class="card-header"><div><h2 class="card-title"><i class="fa fa-file-circle-check text-accent"></i> Revision-paper library</h2><p class="form-hint">Course learning resources shared with eligible students.</p></div></div><div class="stats-grid"><div class="stat-card"><div class="stat-number"><?= (int)$revisionSummary['total'] ?></div><div class="stat-label">Total papers</div></div><div class="stat-card"><div class="stat-number text-green"><?= (int)$revisionSummary['published'] ?></div><div class="stat-label">Published to students</div></div><div class="stat-card"><div class="stat-number text-yellow"><?= (int)$revisionSummary['archived'] ?></div><div class="stat-label">Archived</div></div></div><?php if ($revisionSummary['latest']): ?><div class="table-wrap"><table><thead><tr><th>Paper</th><th>Course</th><th>Shared by</th><th>Status</th><th>Added</th></tr></thead><tbody><?php foreach ($revisionSummary['latest'] as $paper): ?><tr><td class="fw-700"><?= htmlspecialchars($paper['title']) ?></td><td><?= htmlspecialchars($paper['code'] . ' — ' . $paper['course_title']) ?></td><td><?= htmlspecialchars($paper['uploader_name']) ?></td><td><span class="badge badge-<?= $paper['status'] === 'published' ? 'success' : 'pending' ?>"><?= htmlspecialchars(ucfirst($paper['status'])) ?></span></td><td><?= htmlspecialchars(date('M j, Y', strtotime($paper['created_at']))) ?></td></tr><?php endforeach; ?></tbody></table></div><?php else: ?><div class="empty-state compact-empty-state"><p>No revision papers have been shared yet.</p></div><?php endif; ?></section>
<div class="card"><div class="card-header"><h2 class="card-title">Site health &amp; configuration checks</h2></div><ul><?php foreach ($health as $check => $ok): ?><li><span class="badge badge-<?= $ok ? 'success' : 'warning' ?>"><?= $ok ? 'OK' : 'CHECK' ?></span> <?= htmlspecialchars(ucwords(str_replace('_', ' ', $check))) ?></li><?php endforeach; ?></ul><p class="form-hint">Health checks report configuration presence only; secrets are never shown.</p></div>
<section class="card" id="payment-readiness"><div class="card-header"><div><h2 class="card-title"><i class="fa fa-mobile-screen-button text-accent"></i> M-Pesa integration readiness</h2><p class="form-hint">Only configuration presence is reported; secret values are never displayed.</p></div></div><div class="admin-readiness-grid"><?php foreach ([
	'Portal extensions' => $paymentReadiness['extensions_enabled'],
	'Daraja environment selected' => $paymentReadiness['environment'] !== 'invalid',
	'Daraja credentials complete' => $paymentReadiness['credentials_present'],
	'HTTPS callback URL' => $paymentReadiness['callback_https'],
	'PHP cURL available' => $paymentReadiness['curl_available'],
	'M-Pesa runtime switch' => $paymentReadiness['mpesa_enabled'],
	'Admin payments switch' => $paymentReadiness['payments_site_switch'],
] as $check => $ok): ?><div class="readiness-item"><span class="badge badge-<?= $ok ? 'success' : 'warning' ?>"><?= $ok ? 'Ready' : 'Not set' ?></span><span><?= htmlspecialchars($check) ?></span></div><?php endforeach; ?>
<div class="alert alert-warning mt-2"><i class="fa fa-circle-info"></i><div><strong>Current checkout mode: <?= htmlspecialchars($paymentReadiness['integration_mode']) ?>.</strong> This Daraja STK Push requires a registered business shortcode and passkey. The phone field is the student's paying phone; it does not route funds directly to a personal mobile number. Direct person-to-person M-Pesa transfers cannot be automatically confirmed by this STK callback integration.</div></div><p class="form-hint">Payments are disabled by default. Do not enable them until the shortcode/passkey, callback, sandbox tests, and your intended receiving method are confirmed.</p></section>
<?php if (PORTAL_EXTENSIONS_ENABLED): ?><div class="card" id="site-controls"><div class="card-header"><h2 class="card-title">Site feature controls</h2></div><?php foreach ($siteSettings as $settingKey => $settingValue): ?><form method="POST" action="/admin/action.php" class="d-flex gap-1" style="padding:.5rem 0"><input type="hidden" name="csrf_token" value="<?= Auth::csrfToken() ?>"><input type="hidden" name="setting_key" value="<?= htmlspecialchars($settingKey) ?>"><strong style="min-width:18rem"><?= htmlspecialchars(ucwords(str_replace('_',' ',$settingKey))) ?></strong><select name="setting_value"><option value="1" <?= $settingValue==='1'?'selected':'' ?>>Enabled</option><option value="0" <?= $settingValue==='0'?'selected':'' ?>>Disabled</option></select><button class="btn btn-secondary btn-sm" name="action" value="update_setting">Save</button></form><?php endforeach; ?><p class="form-hint">Payments also require MPESA_ENABLED=true and valid Daraja configuration. Feature settings are audited.</p></div><?php endif; ?>
	<div class="card" id="lecturer-approvals"><div class="card-header"><h2 class="card-title">Lecturer approvals</h2></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Applied</th><th>Action</th></tr></thead><tbody><?php foreach ($pendingLecturers as $lecturer): ?><tr><td><?= htmlspecialchars($lecturer['name']) ?></td><td><?= htmlspecialchars($lecturer['email']) ?></td><td><?= htmlspecialchars($lecturer['created_at']) ?></td><td><form method="POST" action="/admin/action.php" style="display:flex;gap:.5rem"><input type="hidden" name="csrf_token" value="<?= Auth::csrfToken() ?>"><input type="hidden" name="lecturer_id" value="<?= (int)$lecturer['id'] ?>"><input name="note" maxlength="500" placeholder="Note (optional)"><button class="btn btn-success btn-sm" name="action" value="approve">Approve</button><button class="btn btn-danger btn-sm" name="action" value="reject">Reject</button></form></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="card" id="users"><div class="card-header"><h2 class="card-title">Users</h2></div><form method="GET" class="d-flex gap-1"><input name="q" value="<?= htmlspecialchars($search) ?>" placeholder="Search name or email"><select name="role"><option value="">All roles</option><?php foreach (['student','lecturer','tutor','admin'] as $r): ?><option <?= $role === $r ? 'selected' : '' ?>><?= $r ?></option><?php endforeach; ?></select><button class="btn btn-secondary">Search</button></form><div class="table-wrap"><table><thead><tr><th>User</th><th>Role</th><?php if(PORTAL_EXTENSIONS_ENABLED): ?><th>Account</th><th>Lecturer approval</th><?php endif; ?><th>Actions</th></tr></thead><tbody><?php foreach ($userPage['rows'] as $row): ?><tr><td><?= htmlspecialchars($row['name']) ?><br><small><?= htmlspecialchars($row['email']) ?></small></td><td><?= htmlspecialchars($row['role']) ?></td><?php if(PORTAL_EXTENSIONS_ENABLED): ?><td><?= htmlspecialchars($row['account_status']) ?></td><td><?= htmlspecialchars($row['lecturer_approval_status'] ?? '—') ?></td><?php endif; ?><td><?php if(PORTAL_EXTENSIONS_ENABLED): ?><form method="POST" action="/admin/action.php" class="d-flex gap-1"><input type="hidden" name="csrf_token" value="<?= Auth::csrfToken() ?>"><input type="hidden" name="user_id" value="<?= (int)$row['id'] ?>"><select name="role"><?php foreach (['student','lecturer','tutor','admin'] as $r): ?><option value="<?= $r ?>" <?= $row['role'] === $r ? 'selected' : '' ?>><?= $r ?></option><?php endforeach; ?></select><select name="account_status"><option value="active" <?= $row['account_status'] === 'active' ? 'selected' : '' ?>>active</option><option value="suspended" <?= $row['account_status'] === 'suspended' ? 'selected' : '' ?>>suspended</option></select><button class="btn btn-secondary btn-sm" name="action" value="update_user">Save</button></form><form method="POST" action="/admin/action.php" onsubmit="return confirm('Permanently delete this account and its owned courses, enrollments, assignments, submissions, payments, sessions, and revision papers? The current and last active admin cannot be deleted.')"><input type="hidden" name="csrf_token" value="<?= Auth::csrfToken() ?>"><input type="hidden" name="user_id" value="<?= (int)$row['id'] ?>"><button class="btn btn-danger btn-sm" name="action" value="delete_user">Delete (no history only)</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><p class="form-hint">Page <?= $page ?> of <?= max(1,$userPage['pages']) ?> · <?= $userPage['total'] ?> users</p></div>
<div class="card" id="courses"><div class="card-header"><h2 class="card-title">Courses</h2></div><div class="table-wrap"><table><thead><tr><th>Course</th><th>Lecturer</th><th>Status</th><th>Enrollments</th><th>Revenue</th><th>Fee (KES)</th><th>Actions</th></tr></thead><tbody><?php foreach ($courses as $course): ?><tr><td><?= htmlspecialchars($course['code'].' — '.$course['title']) ?></td><td><?= htmlspecialchars($course['lecturer_name']) ?></td><td><?= htmlspecialchars($course['status']) ?></td><td><?= (int)$course['enrollments'] ?></td><td>KES <?= number_format((float)$course['revenue'],2) ?></td><td><?php if (PORTAL_EXTENSIONS_ENABLED): ?><form method="POST" action="/admin/action.php" class="d-flex gap-1"><input type="hidden" name="csrf_token" value="<?= Auth::csrfToken() ?>"><input type="hidden" name="course_id" value="<?= (int)$course['id'] ?>"><input name="price" type="number" min="0" max="1000000" step="1" value="<?= htmlspecialchars((string)($course['price'] ?? '')) ?>" placeholder="Free"><button class="btn btn-secondary btn-sm" name="action" value="update_course_fee">Save</button></form><?php else: ?>—<?php endif; ?></td><td><div class="d-flex gap-1"><form method="POST" action="/admin/action.php"><input type="hidden" name="csrf_token" value="<?= Auth::csrfToken() ?>"><input type="hidden" name="course_id" value="<?= (int)$course['id'] ?>"><?php if ($course['status'] === 'suspended'): ?><button class="btn btn-success btn-sm" name="action" value="restore_course">Restore</button><?php else: ?><button class="btn btn-danger btn-sm" name="action" value="suspend_course">Suspend</button><?php endif; ?></form><form method="POST" action="/admin/action.php" onsubmit="return confirm('Permanently delete this course and its enrollments, assignments, submissions, payments, sessions, and revision papers? This cannot be undone.')"><input type="hidden" name="csrf_token" value="<?= Auth::csrfToken() ?>"><input type="hidden" name="course_id" value="<?= (int)$course['id'] ?>"><button class="btn btn-danger btn-sm" name="action" value="delete_course">Delete</button></form></div></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="card" id="payments"><div class="card-header"><h2 class="card-title">Payments</h2></div><form method="GET"><select name="payment_status"><option value="">All statuses</option><?php foreach (['pending','success','failed'] as $status): ?><option value="<?= $status ?>" <?= ($_GET['payment_status'] ?? '') === $status ? 'selected' : '' ?>><?= $status ?></option><?php endforeach; ?></select><select name="course_id"><option value="">All courses</option><?php foreach ($courseOptions as $courseOption): ?><option value="<?= (int)$courseOption['id'] ?>" <?= (int)($_GET['course_id'] ?? 0)===(int)$courseOption['id']?'selected':'' ?>><?= htmlspecialchars($courseOption['code'].' — '.$courseOption['title']) ?></option><?php endforeach; ?></select><input name="student_id" type="number" min="1" placeholder="Student ID" value="<?= htmlspecialchars($_GET['student_id'] ?? '') ?>"><label>From <input name="date_from" type="date" value="<?= htmlspecialchars($_GET['date_from'] ?? '') ?>"></label><label>To <input name="date_to" type="date" value="<?= htmlspecialchars($_GET['date_to'] ?? '') ?>"></label><button class="btn btn-secondary btn-sm">Filter</button></form><div class="table-wrap"><table><thead><tr><th>Student</th><th>Course</th><th>Amount</th><th>Status</th><th>Receipt</th><th>Date</th></tr></thead><tbody><?php foreach ($payments as $payment): ?><tr><td><?= htmlspecialchars($payment['student_name']) ?></td><td><?= htmlspecialchars($payment['course_title']) ?></td><td>KES <?= number_format((float)$payment['amount_paid'],2) ?></td><td><?= htmlspecialchars($payment['payment_status']) ?></td><td><?= htmlspecialchars($payment['mpesa_receipt'] ?? '—') ?></td><td><?= htmlspecialchars($payment['created_at']) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="card" id="audit-log"><div class="card-header"><h2 class="card-title">Recent security/admin audit events</h2></div><div class="table-wrap"><table><thead><tr><th>Time</th><th>Administrator</th><th>Action</th><th>Target</th></tr></thead><tbody><?php foreach ($audit as $event): ?><tr><td><?= htmlspecialchars($event['created_at']) ?></td><td><?= htmlspecialchars($event['admin_name'] ?? 'System') ?></td><td><?= htmlspecialchars($event['action']) ?></td><td><?= htmlspecialchars($event['target_type'] . ' ' . ($event['target_id'] ?? '')) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php include __DIR__ . '/../../views/shared/footer.php'; ?>
